Repository sw-security-web-app/sw-security-web-app_BE, pull requests merged in 2025-02, with the labels that each got.

#26 [SCRUM-25]Security 설정 및 JWT구현
  build.gradle
  src/main/java/example/demo/config/CommonConfiguration.java
  src/main/java/example/demo/domain/member/Member.java
  src/main/java/example/demo/domain/member/SecurityMember.java
  src/main/java/example/demo/domain/member/api/MemberService.java
  src/main/java/example/demo/domain/member/api/MemberServiceImpl.java
  src/main/java/example/demo/domain/member/dto/request/MemberRequestDto.java
  src/main/java/example/demo/domain/member/dto/request/SmsCertificationRequestDto.java
  src/main/java/example/demo/domain/member/repository/MemberRepository.java
  src/main/java/example/demo/domain/member/sms/SmsServiceImpl.java
  src/main/java/example/demo/security/auth/AuthErrorCode.java
  src/main/java/example/demo/security/auth/CustomMemberDetailService.java
  src/main/java/example/demo/security/auth/CustomMemberDetails.java
  src/main/java/example/demo/security/auth/api/AuthApiController.java
  src/main/java/example/demo/security/auth/api/AuthService.java
  src/main/java/example/demo/security/auth/api/AuthServiceImpl.java
  src/main/java/example/demo/security/auth/dto/CustomMemberInfoDto.java
  src/main/java/example/demo/security/auth/dto/MemberLoginDto.java
  src/main/java/example/demo/security/config/CustomAccessDeniedHandler.java
  src/main/java/example/demo/security/config/CustomAuthenticationEntryPoint.java
  src/main/java/example/demo/security/config/PasswordEncoderConfig.java
  src/main/java/example/demo/security/config/SecurityConfig.java
  src/main/java/example/demo/security/util/JwtAuthFilter.java
  src/main/java/example/demo/security/util/JwtUtil.java
  src/main/java/example/demo/security/util/SecurityUtil.java
  src/test/java/example/demo/domain/member/api/MemberServiceTest.java
  src/test/java/example/demo/domain/member/dto/request/MemberRequestDtoTest.java
  src/test/java/example/demo/domain/member/mail/MailServiceTest.java
  src/test/java/example/demo/domain/member/repository/MemberRepositoryTest.java
  src/test/java/example/demo/util/CreateRandomTest.java
Labels: 💫feat, 중요도⭐️⭐️⭐️

#34 [SCRUM-40] 회원가입시 회사 연관관계 수정
  build.gradle
  src/main/java/example/demo/domain/company/Company.java
  src/main/java/example/demo/domain/company/repository/CompanyRepository.java
  src/main/java/example/demo/domain/member/Member.java
  src/main/java/example/demo/domain/member/api/MemberServiceImpl.java
  src/test/java/example/demo/domain/company/CompanyCustomRepositoryImplTest.java
  src/test/java/example/demo/domain/member/api/MemberServiceTest.java
Labels: 🐛fix, 중요도⭐️⭐️

#31 [SCRUM-38]회원정보 반환 API
  build.gradle
  src/main/java/example/demo/DemoApplication.java
  src/main/java/example/demo/config/JpaAuditingConfiguration.java
  src/main/java/example/demo/domain/member/MemberErrorCode.java
  src/main/java/example/demo/domain/member/api/MemberController.java
  src/main/java/example/demo/domain/member/api/MemberService.java
  src/main/java/example/demo/domain/member/api/MemberServiceImpl.java
  src/main/java/example/demo/domain/member/dto/request/MemberPhoneAndEmailRequestDto.java
  src/main/java/example/demo/domain/member/dto/request/MemberRequestDto.java
  src/main/java/example/demo/domain/member/dto/response/FindEmailResponseDto.java
  src/main/java/example/demo/domain/member/dto/response/MemberInfoResponseDto.java
  src/main/java/example/demo/domain/member/mail/MailController.java
  src/main/java/example/demo/domain/member/mail/MailService.java
  src/main/java/example/demo/domain/member/mail/MailServiceImpl.java
  src/main/java/example/demo/domain/member/repository/MemberCustomRepository.java
  src/main/java/example/demo/domain/member/repository/MemberCustomRepositoryImpl.java
  src/main/java/example/demo/domain/member/repository/MemberRepository.java
  src/main/java/example/demo/domain/member/sms/SmsController.java
  src/main/java/example/demo/domain/member/sms/SmsService.java
  src/main/java/example/demo/domain/member/sms/SmsServiceImpl.java
  src/main/java/example/demo/domain/member/sms/SmsUtil.java
  src/main/java/example/demo/security/auth/api/AuthApiController.java
  src/main/java/example/demo/security/config/SecurityConfig.java
  src/main/java/example/demo/security/util/JwtAuthFilter.java
  src/test/java/example/demo/domain/member/api/MemberControllerTest.java
  src/test/java/example/demo/domain/member/api/MemberServiceTest.java
  src/test/java/example/demo/domain/member/mail/MailServiceTest.java
  src/test/java/example/demo/domain/member/repository/MemberCustomRepositoryImplTest.java
  src/test/java/example/demo/domain/member/repository/MemberRepositoryTest.java
Labels: 💫feat, 중요도⭐️⭐️

#35 [SCRUM-39]QueryDsl를 이용한 직원 정보 조회
  src/main/java/example/demo/domain/company/api/CompanyController.java
  src/main/java/example/demo/domain/company/api/CompanyService.java
  src/main/java/example/demo/domain/company/api/CompanyServiceImpl.java
  src/main/java/example/demo/domain/company/dto/response/CompanyResponseDto.java
  src/main/java/example/demo/domain/company/repository/CompanyCustomRepository.java
  src/main/java/example/demo/domain/company/repository/CompanyCustomRepositoryImpl.java
  src/main/java/example/demo/domain/member/MemberErrorCode.java
  src/main/java/example/demo/domain/member/api/MemberController.java
  src/main/java/example/demo/domain/member/api/MemberService.java
  src/main/java/example/demo/domain/member/api/MemberServiceImpl.java
  src/main/java/example/demo/domain/member/dto/response/CompanyEmployeeResponseDto.java
  src/main/java/example/demo/domain/member/repository/MemberCustomRepository.java
  src/main/java/example/demo/domain/member/repository/MemberCustomRepositoryImpl.java
  src/main/java/example/demo/util/CompanyPosition.java
  src/main/java/example/demo/util/QueryDslUtil.java
  src/test/java/example/demo/domain/company/api/CompanyServiceTest.java
  src/test/java/example/demo/domain/member/MemberCustomRepositoryImplTest.java
  src/test/java/example/demo/domain/member/api/MemberServiceTest.java
  src/test/java/example/demo/domain/member/repository/MemberCustomRepositoryImplTest.java
  src/test/java/example/demo/util/QueryDslUtilTest.java
Labels: ✅test, 💫feat, 중요도⭐️⭐️

#37 [SCRUM-35] 생성형 AI 3개 모델 API 구현
  build.gradle
  src/main/generated/example/demo/domain/QBaseEntity.java
  src/main/generated/example/demo/domain/company/QCompany.java
  src/main/generated/example/demo/domain/company/dto/QCompanyCodeDto.java
  src/main/generated/example/demo/domain/company/dto/QCompanyInfoWithUuidDto.java
  src/main/generated/example/demo/domain/member/QMember.java
  src/main/java/example/demo/domain/chat/claude/ClaudeErrorCode.java
  src/main/java/example/demo/domain/chat/claude/controller/ClaudeController.java
  src/main/java/example/demo/domain/chat/claude/dto/ClaudeRequestDto.java
  src/main/java/example/demo/domain/chat/claude/dto/ClaudeResponseDto.java
  src/main/java/example/demo/domain/chat/claude/service/ClaudeService.java
  src/main/java/example/demo/domain/chat/claude/service/ClaudeServiceImpl.java
  src/main/java/example/demo/domain/chat/gemini/GeminiErrorCode.java
  src/main/java/example/demo/domain/chat/gemini/controller/GeminiController.java
  src/main/java/example/demo/domain/chat/gemini/dto/GeminiRequestDto.java
  src/main/java/example/demo/domain/chat/gemini/dto/GeminiResponseDto.java
  src/main/java/example/demo/domain/chat/gemini/service/GeminiService.java
  src/main/java/example/demo/domain/chat/gemini/service/GeminiServiceImpl.java
  src/main/java/example/demo/domain/chat/gpt/GptErrorCode.java
  src/main/java/example/demo/domain/chat/gpt/config/ChatGPTConfig.java
  src/main/java/example/demo/domain/chat/gpt/controller/ChatGPTController.java
  src/main/java/example/demo/domain/chat/gpt/dto/ChatCompletionDto.java
  src/main/java/example/demo/domain/chat/gpt/dto/ChatRequestMsgDto.java
  src/main/java/example/demo/domain/chat/gpt/dto/CompletionDto.java
  src/main/java/example/demo/domain/chat/gpt/service/ChatGPTService.java
  src/main/java/example/demo/domain/chat/gpt/service/ChatGPTServiceImpl.java
Labels: 💫feat, 중요도⭐️⭐️⭐️

#39 [SCRUM-39] merge:충돌해결
  src/main/java/example/demo/domain/member/MemberErrorCode.java
  src/main/java/example/demo/domain/member/api/MemberServiceImpl.java
  src/main/java/example/demo/domain/member/repository/MemberCustomRepositoryImpl.java
  src/main/java/example/demo/util/QueryDslUtil.java
Labels: 🛠️merge, 중요도⭐️

#42 [SCRUM-50] 리프레쉬 토큰 구현
  src/main/java/example/demo/data/RedisCustomService.java
  src/main/java/example/demo/data/RedisCustomServiceImpl.java
  src/main/java/example/demo/domain/member/api/MemberServiceImpl.java
  src/main/java/example/demo/domain/member/dto/response/MemberInfoResponseDto.java
  src/main/java/example/demo/domain/member/repository/MemberCustomRepositoryImpl.java
  src/main/java/example/demo/security/auth/AuthErrorCode.java
  src/main/java/example/demo/security/auth/api/AuthApiController.java
  src/main/java/example/demo/security/auth/api/AuthService.java
  src/main/java/example/demo/security/auth/api/AuthServiceImpl.java
  src/main/java/example/demo/security/auth/dto/AccessTokenResponseDto.java
  src/main/java/example/demo/security/config/SecurityConfig.java
  src/main/java/example/demo/security/domain/RefreshToken.java
  src/main/java/example/demo/security/exception/SecurityErrorCode.java
  src/main/java/example/demo/security/util/JwtUtil.java
Labels: 💫feat, 중요도⭐️⭐️⭐️

#43 [SCRUM-44] pdf변환 및 AI서버 전송 구현
  build.gradle
  src/main/java/example/demo/domain/chatting/api/PdfController.java
  src/main/java/example/demo/domain/chatting/api/PdfErrorCode.java
  src/main/java/example/demo/domain/chatting/api/PdfService.java
  src/main/java/example/demo/domain/chatting/api/PdfServiceImpl.java
  src/main/java/example/demo/domain/chatting/util/PdfConverter.java
  src/main/java/example/demo/domain/member/api/MemberServiceImpl.java
  src/main/java/example/demo/security/auth/CustomMemberDetails.java
  src/main/java/example/demo/security/util/JwtUtil.java
Labels: ✅test, 💫feat, 중요도⭐️⭐️

#45 [SCRUM-54] 가입 이메일 찾기 리팩토링
  src/main/java/example/demo/domain/member/dto/request/MemberFindEmailRequestDto.java
  src/main/java/example/demo/domain/member/mail/MailServiceImpl.java
  src/main/java/example/demo/domain/member/repository/MemberCustomRepository.java
  src/main/java/example/demo/domain/member/repository/MemberCustomRepositoryImpl.java
  src/main/java/example/demo/domain/member/sms/SmsController.java
  src/main/java/example/demo/domain/member/sms/SmsService.java
  src/main/java/example/demo/domain/member/sms/SmsServiceImpl.java
  src/test/java/example/demo/domain/member/repository/MemberCustomRepositoryImplTest.java
Labels: ♻️refactoring, ✅test, 중요도⭐️⭐️

#49 [SCRUM-56] 최신 대화방 4개 및 Preview 불러오기 & 유저당 대화방 생성 제한
  src/main/java/example/demo/domain/chat/controller/ChatRoomController.java
  src/main/java/example/demo/domain/chat/dto/ChatRoomRecentResponseDto.java
  src/main/java/example/demo/domain/chat/dto/ChatRoomRequestDto.java
  src/main/java/example/demo/domain/chat/repository/ChatRepository.java
  src/main/java/example/demo/domain/chat/repository/ChatRepositoryCustom.java
  src/main/java/example/demo/domain/chat/repository/ChatRepositoryCustomImpl.java
  src/main/java/example/demo/domain/chat/repository/ChatRoomRepositoryCustom.java
  src/main/java/example/demo/domain/chat/repository/ChatRoomRepositoryCustomImpl.java
  src/main/java/example/demo/domain/chat/service/ChatRoomService.java
  src/main/java/example/demo/domain/chat/service/ChatRoomServiceImpl.java
Labels: ♻️refactoring, 💫feat, 중요도⭐️⭐️

#51 [SCRUM-59] feat: Python Server Util Class 구현 및 ServiceImpl 적용
  src/main/java/example/demo/domain/chat/claude/service/ClaudeServiceImpl.java
  src/main/java/example/demo/domain/chat/gemini/service/GeminiServiceImpl.java
  src/main/java/example/demo/domain/chat/gpt/service/ChatGPTServiceImpl.java
  src/main/java/example/demo/util/PythonServerUtil.java
  src/main/java/example/demo/util/UtilErrorCode.java
Labels: 💫feat, 중요도⭐️⭐️⭐️
