Repository sw-security-web-app/sw-security-web-app_BE, pull requests merged in 2025-03, with the labels that each got.

#52 [SCRUM-57] 회원 비밀번호 수정 / 로그인 5회 초과 시 계정 일시 차단
  src/main/java/example/demo/common/ResponseDto.java
  src/main/java/example/demo/data/RedisCustomService.java
  src/main/java/example/demo/data/RedisCustomServiceImpl.java
  src/main/java/example/demo/domain/member/Member.java
  src/main/java/example/demo/security/auth/AuthErrorCode.java
  src/main/java/example/demo/security/auth/CustomMemberDetailService.java
  src/main/java/example/demo/security/auth/api/AuthApiController.java
  src/main/java/example/demo/security/auth/api/AuthService.java
  src/main/java/example/demo/security/auth/api/AuthServiceImpl.java
  src/main/java/example/demo/security/auth/dto/ChangePasswordRequestDto.java
  src/main/java/example/demo/security/auth/dto/CustomMemberInfoDto.java
  src/main/java/example/demo/security/config/CustomAuthenticationFailureHandler.java
  src/main/java/example/demo/security/config/SecurityConfig.java
  src/test/java/example/demo/domain/member/api/MemberControllerTest.java
  src/test/java/example/demo/domain/member/repository/MemberRepositoryTest.java
  src/test/java/example/demo/security/auth/api/AuthApiControllerTest.java
  src/test/java/example/demo/security/auth/api/AuthServiceImplTest.java
Labels: 💫feat, 중요도⭐️⭐️⭐️

#58 [SCRUM-68] setting: Config 수정 및 HealthCheckController 설정
  src/main/java/example/demo/security/HealthCheckController.java
  src/main/java/example/demo/security/config/SecurityConfig.java
Labels: 📌chore, 🚑hotfix, 중요도⭐️⭐️⭐️

#61 [SCRUM-56] AI Model Type을 기준으로 최신 대화방 및 대화방 조회 기능 구현
  src/main/java/example/demo/domain/chat/controller/ChatRoomController.java
  src/main/java/example/demo/domain/chat/dto/ChatRoomGetRequestDto.java
  src/main/java/example/demo/domain/chat/dto/ChatRoomGetResponseDto.java
  src/main/java/example/demo/domain/chat/repository/ChatRepository.java
  src/main/java/example/demo/domain/chat/repository/ChatRoomRepository.java
  src/main/java/example/demo/domain/chat/repository/ChatRoomRepositoryCustom.java
  src/main/java/example/demo/domain/chat/repository/ChatRoomRepositoryCustomImpl.java
  src/main/java/example/demo/domain/chat/service/ChatRoomService.java
  src/main/java/example/demo/domain/chat/service/ChatRoomServiceImpl.java
Labels: ♻️refactoring, 💫feat, 중요도⭐️⭐️⭐️

#62 [SCRUM-65] Slice쿼리를 이용한 무한 스크롤 구현
  .github/workflows/build-deploy.yml
  appspec.yml
  build.gradle
  scripts/deploy.sh
  src/main/java/example/demo/domain/chat/claude/service/ClaudeServiceImpl.java
  src/main/java/example/demo/domain/chat/controller/ChatController.java
  src/main/java/example/demo/domain/chat/controller/ChatRoomController.java
  src/main/java/example/demo/domain/chat/dto/request/ChatRoomRequestDto.java
  src/main/java/example/demo/domain/chat/dto/response/ChatDetailResponseDto.java
  src/main/java/example/demo/domain/chat/dto/response/ChatRoomRecentResponseDto.java
  src/main/java/example/demo/domain/chat/dto/response/ChatRoomResponseDto.java
  src/main/java/example/demo/domain/chat/dto/response/ChatTotalDetailResponseDto.java
  src/main/java/example/demo/domain/chat/gemini/service/GeminiServiceImpl.java
  src/main/java/example/demo/domain/chat/gpt/service/ChatGPTServiceImpl.java
  src/main/java/example/demo/domain/chat/repository/ChatRepositoryCustom.java
  src/main/java/example/demo/domain/chat/repository/ChatRepositoryCustomImpl.java
  src/main/java/example/demo/domain/chat/repository/ChatRoomRepositoryCustom.java
  src/main/java/example/demo/domain/chat/repository/ChatRoomRepositoryCustomImpl.java
  src/main/java/example/demo/domain/chat/service/ChatRoomService.java
  src/main/java/example/demo/domain/chat/service/ChatRoomServiceImpl.java
  src/main/java/example/demo/domain/chat/service/ChatService.java
  src/main/java/example/demo/domain/chat/service/ChatServiceImpl.java
  src/main/java/example/demo/security/config/SecurityConfig.java
  src/main/java/example/demo/verification/controller/VerificationController.java
Labels: 💫feat, 중요도⭐️⭐️⭐️

#67 [SCRUM-72] 유저 계정 잠금 활성화 및 비활성화 , 회원 탈퇴
  src/main/java/example/demo/domain/member/Member.java
  src/main/java/example/demo/domain/member/dto/response/CompanyEmployeeResponseDto.java
  src/main/java/example/demo/domain/member/repository/MemberCustomRepositoryImpl.java
  src/main/java/example/demo/security/auth/AuthErrorCode.java
  src/main/java/example/demo/security/auth/CustomMemberDetailService.java
  src/main/java/example/demo/security/auth/api/AuthApiController.java
  src/main/java/example/demo/security/auth/api/AuthService.java
  src/main/java/example/demo/security/auth/api/AuthServiceImpl.java
  src/main/java/example/demo/security/config/CustomAuthenticationEntryPoint.java
Labels: 💫feat, 중요도⭐️⭐️⭐️

#69 [SCRUM-76] 검열 AI 모델 생성 유무 검증 구현
  build.gradle
  src/main/java/example/demo/config/ResponseDto.java
  src/main/java/example/demo/domain/chat/claude/service/ClaudeServiceImpl.java
  src/main/java/example/demo/domain/chat/gemini/service/GeminiServiceImpl.java
  src/main/java/example/demo/domain/chat/gpt/service/ChatGPTServiceImpl.java
  src/main/java/example/demo/domain/chat/repository/ChatRoomRepository.java
  src/main/java/example/demo/domain/chat/service/ChatRoomServiceImpl.java
  src/main/java/example/demo/domain/chatting/api/PdfController.java
  src/main/java/example/demo/domain/chatting/api/PdfService.java
  src/main/java/example/demo/domain/chatting/api/PdfServiceImpl.java
  src/main/java/example/demo/domain/company/Company.java
  src/main/java/example/demo/domain/company/api/CompanyController.java
  src/main/java/example/demo/security/auth/api/AuthServiceImpl.java
  src/main/java/example/demo/security/auth/dto/AccessTokenResponseDto.java
  src/main/java/example/demo/security/auth/dto/ChangePasswordRequestDto.java
  src/main/java/example/demo/security/config/SecurityConfig.java
  src/main/java/example/demo/util/pdf/PdfErrorCode.java
  src/main/java/example/demo/util/pdf/PdfService.java
  src/main/java/example/demo/util/pdf/PdfServiceImpl.java
  src/main/java/example/demo/verification/controller/VerificationController.java
  src/main/java/example/demo/verification/dto/SecurityFileRequestDto.java
  src/main/java/example/demo/verification/error/VerificationErrorCode.java
  src/main/java/example/demo/verification/service/VerificationService.java
  src/main/java/example/demo/verification/service/VerificationServiceImpl.java
  src/main/java/example/demo/verification/util/PdfConverter.java
  src/main/java/example/demo/verification/util/PythonServerUtil.java
  src/main/resources/application.yml
Labels: 💫feat, 중요도⭐️⭐️⭐️

#66 [SCRUM-56] fix: 최근 대화방 4개 반환 시 가장 최근에 이루어진 대화의 날짜 반환
  src/main/java/example/demo/domain/chat/dto/ChatRoomGetResponseDto.java
  src/main/java/example/demo/domain/chat/dto/response/ChatRoomRecentResponseDto.java
  src/main/java/example/demo/domain/chat/repository/ChatRoomRepository.java
  src/main/java/example/demo/domain/chat/service/ChatRoomServiceImpl.java
Labels: ♻️refactoring, 🐛fix, 중요도⭐️

#72 [SCRUM-79] Python Util 수정 및 최종 수정본
  src/main/java/example/demo/domain/chat/claude/service/ClaudeServiceImpl.java
  src/main/java/example/demo/domain/chat/controller/ChatController.java
  src/main/java/example/demo/domain/chat/controller/ChatRoomController.java
  src/main/java/example/demo/domain/chat/dto/ChatRoomGetResponseDto.java
  src/main/java/example/demo/domain/chat/dto/request/ChatDto.java
  src/main/java/example/demo/domain/chat/dto/request/ChatRoomGetRequestDto.java
  src/main/java/example/demo/domain/chat/dto/response/ChatRoomGetResponseDto.java
  src/main/java/example/demo/domain/chat/gemini/service/GeminiServiceImpl.java
  src/main/java/example/demo/domain/chat/gpt/service/ChatGPTServiceImpl.java
  src/main/java/example/demo/domain/chat/repository/ChatRepositoryCustomImpl.java
  src/main/java/example/demo/domain/chat/repository/ChatRoomRepository.java
  src/main/java/example/demo/domain/chat/repository/ChatRoomRepositoryCustom.java
  src/main/java/example/demo/domain/chat/repository/ChatRoomRepositoryCustomImpl.java
  src/main/java/example/demo/domain/chat/service/ChatRoomService.java
  src/main/java/example/demo/domain/chat/service/ChatRoomServiceImpl.java
  src/main/java/example/demo/domain/chat/service/ChatService.java
  src/main/java/example/demo/domain/chat/service/ChatServiceImpl.java
  src/main/java/example/demo/domain/company/Company.java
  src/main/java/example/demo/domain/member/MemberErrorCode.java
  src/main/java/example/demo/domain/member/api/MemberServiceImpl.java
  src/main/java/example/demo/security/auth/AuthErrorCode.java
  src/main/java/example/demo/security/auth/api/AuthServiceImpl.java
  src/main/java/example/demo/security/auth/dto/AccessTokenResponseDto.java
  src/main/java/example/demo/security/config/CustomAuthenticationEntryPoint.java
  src/main/java/example/demo/security/config/SecurityConfig.java
  src/main/java/example/demo/util/UtilErrorCode.java
  src/main/java/example/demo/verification/dto/SecurityFileRequestDto.java
  src/main/java/example/demo/verification/error/VerificationErrorCode.java
  src/main/java/example/demo/verification/service/VerificationService.java
  src/main/java/example/demo/verification/service/VerificationServiceImpl.java
  src/main/java/example/demo/verification/util/PythonServerUtil.java
  src/test/java/example/demo/domain/chat/controller/ChatAIControllerTest.java
Labels: 🐛fix, 💫feat, 중요도⭐️⭐️⭐️

#73 🔖최종 기능 구현 및 최초 릴리즈
  src/main/java/example/demo/domain/chat/claude/service/ClaudeServiceImpl.java
  src/main/java/example/demo/domain/chat/controller/ChatController.java
  src/main/java/example/demo/domain/chat/dto/ChatRoomGetResponseDto.java
  src/main/java/example/demo/domain/chat/gemini/service/GeminiServiceImpl.java
  src/main/java/example/demo/domain/chat/gpt/service/ChatGPTServiceImpl.java
  src/main/java/example/demo/domain/chat/repository/ChatRepositoryCustomImpl.java
  src/main/java/example/demo/domain/chat/repository/ChatRoomRepositoryCustomImpl.java
  src/main/java/example/demo/domain/member/MemberErrorCode.java
  src/main/java/example/demo/domain/member/api/MemberServiceImpl.java
  src/main/java/example/demo/security/auth/api/AuthServiceImpl.java
  src/main/java/example/demo/security/config/SecurityConfig.java
  src/main/java/example/demo/util/UtilErrorCode.java
  src/main/java/example/demo/verification/dto/SecurityFileRequestDto.java
  src/main/java/example/demo/verification/error/VerificationErrorCode.java
  src/main/java/example/demo/verification/service/VerificationService.java
  src/main/java/example/demo/verification/service/VerificationServiceImpl.java
  src/main/java/example/demo/verification/util/PythonServerUtil.java
Labels: 👷CICD, 🔖release, 🛠️merge

#75 [SCRUM-83] WhiteList수정
  src/main/java/example/demo/security/config/SecurityConfig.java
Labels: 🚑hotfix, 중요도⭐️⭐️⭐️

#77 [SCRUM-84] Bearer제거 메소드 추가
  src/main/java/example/demo/security/util/JwtUtil.java
Labels: 🚑hotfix, 중요도⭐️⭐️⭐️

#78 [SCRUM-84] refreshToken 발급 수정
  src/main/java/example/demo/security/auth/api/AuthServiceImpl.java
Labels: 🚑hotfix, 중요도⭐️⭐️⭐️

#80 [SCRUM-84] 멤버 삭제 시 참조 키 NULL오류 처리
  src/main/java/example/demo/domain/chat/Chat.java
  src/main/java/example/demo/domain/chat/ChatRoom.java
Labels: 🚑hotfix, 중요도⭐️⭐️⭐️

#82 hotfix : 컬럼 다시 수정
  src/main/java/example/demo/domain/chat/ChatRoom.java
Labels: 🚑hotfix

#85 [SCRUM-85] fix:새 비밀번호 발급 로직 수정
  src/main/java/example/demo/util/CreateRandom.java
Labels: 🐛fix, 🚑hotfix, 중요도⭐️⭐️⭐️
